# Generated by Django 4.2.5 on 2024-03-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accuwheather_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuwheather',
            name='temp',
            field=models.FloatField(),
        ),
    ]
