# Generated by Django 4.2.5 on 2024-03-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accuwheather_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accuwheather',
            old_name='date',
            new_name='time',
        ),
    ]
