# Generated by Django 4.2.1 on 2023-06-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_special',
        ),
    ]
