# Generated by Django 4.2.5 on 2024-03-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(1, 'on'), (0, 'off')])),
                ('color', models.CharField(default='blue', max_length=10)),
                ('btn', models.CharField(default='blue', max_length=10)),
                ('element', models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز')], max_length=3)),
                ('password', models.CharField(max_length=50)),
                ('data', models.IntegerField(null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('locate', models.CharField(choices=[('معمولی', 'معمولی'), ('گرمایی۱', 'گرمایی۱'), ('گرمایی۲', 'گرمایی۲'), ('گرمایی۳', 'گرمایی۳'), ('گرمایی۴', 'گرمایی۴')], max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('pccode', models.CharField(max_length=10)),
                ('electricity_number', models.CharField(max_length=14)),
                ('gaz_number', models.CharField(max_length=14)),
                ('whater_number', models.CharField(max_length=14)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
                ('description', models.TextField()),
                ('visible', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('time2', models.TimeField()),
                ('data', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'on'), (0, 'off')])),
                ('isPackMode', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeOfDevice', to='home.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(choices=[(0, 'توقف'), (1, 'شروع'), (2, 'خطر')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField()),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('forever', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home')),
            ],
        ),
        migrations.CreateModel(
            name='localLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('usage', models.CharField(max_length=10000000000)),
                ('detail', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GUIOrderClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(choices=[(0, 'توقف'), (1, 'شروع'), (2, 'خطر')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('color', models.CharField(default='blue', max_length=10)),
                ('btn', models.CharField(default='blue', max_length=10)),
                ('data', models.IntegerField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home')),
            ],
        ),
        migrations.CreateModel(
            name='GrafData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_usage', models.IntegerField()),
                ('is_fire', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('isEarthHum', models.BooleanField()),
                ('hum', models.FloatField()),
                ('gas', models.IntegerField()),
                ('motion', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
