# Generated by Django 4.2.5 on 2024-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_grafdata_temp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='blue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='green',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='red',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timeofdevice',
            name='blue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timeofdevice',
            name='green',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timeofdevice',
            name='red',
            field=models.IntegerField(null=True),
        ),
    ]
