# Generated by Django 4.2.5 on 2024-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_device_blue_device_green_device_red_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiorderclassmodel',
            name='blue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guiorderclassmodel',
            name='green',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guiorderclassmodel',
            name='red',
            field=models.IntegerField(null=True),
        ),
    ]
