# Generated by Django 4.2.5 on 2024-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.IntegerField(choices=[(0, 'تغییر پکیج'), (1, 'پرسیدن سوال'), (2, 'گزارش باگ')]),
        ),
    ]
