# Generated by Django 4.2.5 on 2024-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ticket_response_alter_ticket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
    ]
