# Generated by Django 4.2.1 on 2023-06-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/obj/')),
                ('thumbnail2', models.ImageField(upload_to='images/obj/')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('masraf', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('offprice', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cart_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=10)),
                ('count', models.IntegerField()),
                ('obj', models.ManyToManyField(to='shop.object')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
