# generated By django in django-core-settings-generator-file-applications-apps-generate usging Django4.2
from django.apps import AppConfig


class ApiConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api'
